{{- $repo := .Values.image.repository -}}
{{- $tag := .Values.image.tag -}}
{{- $port := .Values.ports.containerPort -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCounts.v1 }}
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
        - name: order-service
          image: {{ printf "%s:%s" $repo $tag }}
          env:
            - name: APP_VERSION
              value: "v1"
          ports:
            - containerPort: {{ $port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCounts.v2 }}
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: order-service
          image: {{ printf "%s:%s" $repo $tag }}
          env:
            - name: APP_VERSION
              value: "v2"
          ports:
            - containerPort: {{ $port }}
